---
- hosts: web
  become: true
  roles:
    - role: nginxinc.nginx

  tasks:
  - name: Synchronize images on all web servers.
    synchronize:
      src: ./images
      dest: /var/www/virtualHosts/www.achhome.net/html